# Generated by Django 4.1.3 on 2022-12-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("distroapp", "0002_alter_distrouser_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distrouser",
            name="plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="distroapp.plan",
            ),
        ),
    ]
