# Generated by Django 4.1.3 on 2022-12-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distroapp", "0004_alter_distrouser_options_distrouser_date_joined_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distrouser",
            name="username",
        ),
        migrations.AlterField(
            model_name="distrouser",
            name="account_number",
            field=models.IntegerField(default=543434436, null=True),
        ),
    ]
