# Generated by Django 4.1.3 on 2022-12-24 17:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("distroapp", "0005_remove_distrouser_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distrouser",
            name="account_number",
            field=models.IntegerField(default=543976056, null=True),
        ),
        migrations.AlterField(
            model_name="distrouser",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="distroapp.plan",
            ),
        ),
        migrations.AlterField(
            model_name="distrouser",
            name="user_id",
            field=models.CharField(default=uuid.uuid4, max_length=37, unique=True),
        ),
    ]
