# Generated by Django 4.1.3 on 2022-12-24 21:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("distroapp", "0007_alter_distrouser_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distrouser",
            name="account_number",
            field=models.IntegerField(default=543574822, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="distrouser",
            name="user_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
