# Generated by Django 4.1.3 on 2022-12-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distroapp", "0008_alter_distrouser_account_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distrouser",
            name="account_number",
            field=models.IntegerField(default=543198025, null=True, unique=True),
        ),
    ]
