# Generated by Django 4.1.3 on 2022-12-24 21:07

import distroapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distroapp", "0009_alter_distrouser_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distrouser",
            name="account_number",
            field=models.IntegerField(
                default=distroapp.models.generate_account_number, null=True, unique=True
            ),
        ),
    ]
