# Generated by Django 4.1.3 on 2023-01-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distroapp", "0010_alter_distrouser_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="price",
            field=models.FloatField(),
        ),
    ]
