# Generated by Django 4.1.3 on 2023-01-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distroapp", "0011_alter_plan_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="distrouser",
            name="plan_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="duration",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
