# Generated by Django 4.1.3 on 2023-01-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distroapp", "0012_distrouser_plan_start_date_plan_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
