# Generated by Django 3.2.16 on 2023-01-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distroapp', '0014_alter_plan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrouser',
            name='plan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
